- name: Run Database
  docker_container:
    name: database
    image: perrinebouey/devops:database
    networks:
      - name: app-network
    env:
      POSTGRES_PASSWORD: pwd
      POSTGRES_USER: usr
      POSTGRES_DB: db